# -*- coding: utf-8 -*-
"""GenAI_Linkedin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-9Eef0Bq216hCaT0QZm1fAvo6caIkrp
"""

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from datetime import datetime
from zoneinfo import ZoneInfo
import random

# ===============================
# STEP 1: SYSTEM PROMPT
# ===============================

SYSTEM_PROMPT = """
You are a simple AI agent.
You answer user queries using tools, memory, and basic knowledge.
"""

# ===============================
# STEP 2: LOCAL EMBEDDING MODEL
# ===============================

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# ===============================
# STEP 3: MEMORY (FAISS VECTOR STORE)
# ===============================

memory_texts = []
faiss_index = None

def add_to_memory(text):
    memory_texts.append(text)

def build_faiss_index():
    global faiss_index
    embeddings = embedding_model.encode(memory_texts)
    dim = embeddings.shape[1]
    faiss_index = faiss.IndexFlatL2(dim)
    faiss_index.add(np.array(embeddings))

def retrieve_memory(query, k=1):
    if faiss_index is None:
        return None
    query_vec = embedding_model.encode([query])
    _, indices = faiss_index.search(np.array(query_vec), k)
    return memory_texts[indices[0][0]]

# ===============================
# STEP 4: TOOLS
# ===============================

def get_india_time():
    return datetime.now(ZoneInfo("Asia/Kolkata")).strftime("%Y-%m-%d %H:%M:%S")

TOOLS = {
    "time": get_india_time
}

# ===============================
# STEP 5: KNOWLEDGE BASE
# ===============================

KNOWLEDGE_BASE = {
    "italy_cities": ["Rome", "Milan", "Venice", "Florence", "Naples"]
}

# ===============================
# STEP 6: ORCHESTRATION LOGIC
# ===============================

def agent_think(user_input):
    text = user_input.lower()

    # Tool: Time (India)
    if "time" in text and "india" in text:
        return f"The current time in India is {TOOLS['time']()}"

    # Factual knowledge
    if "city" in text and "italy" in text:
        return f"A city in Italy is {random.choice(KNOWLEDGE_BASE['italy_cities'])}"

    # Memory retrieval
    retrieved = retrieve_memory(user_input)
    if retrieved:
        return f"I remember this: {retrieved}"

    return "I do not have enough information to answer that."

# ===============================
# STEP 7: USER INTERFACE (CLI)
# ===============================

def run_agent():
    print("AI Agent started. Type 'exit' to stop.\n")

    # Initial memory
    add_to_memory("AI agents use memory to improve responses")
    add_to_memory("FAISS enables fast similarity search")
    add_to_memory("Tools help agents perform actions")

    build_faiss_index()

    while True:
        user_input = input("You: ")

        if user_input.lower() == "exit":
            print("Agent stopped.")
            break

        response = agent_think(user_input)
        print("Agent:", response)

# ===============================
# MAIN
# ===============================

if __name__ == "__main__":
    run_agent()